views/image-view.ejs

`userID` is not used. The session user ID is used instead.

Remove userID from comments request

---

lib/database-ops.js

Report from https://lgtm.com/projects/g/Coteh/simpleimage/?mode=list&id=js%2Fsql-injection
Injecting the `username` field with something like `{"$gt": ""}` doesn't end up being very useful anyways, as the handler will only grab the first result. However, this fix will now make it impossible to do an injection at all here.

Fix NoSQL injection with user login

---

assets/js/file-upload.js
lib/routes/route.js
package-lock.json
package.json
views/image-view.ejs
views/index.ejs
views/login-view.ejs
views/register-view.ejs
views/user-menu-view.ejs
views/user-mobile-menu-view.ejs

See LGTM report: https://lgtm.com/projects/g/Coteh/simpleimage/alerts/?mode=list&severity=error&tag=external%2Fcwe%2Fcwe-352
Added `csurf`, implemented CSRF token passing into form requests (hidden form element for non-multipart forms, and as a request header for multipart upload form), and enabled double submit. (by enabling the `cookie` option within `csurf`)

Add CSRF middleware

---

Makefile
docker-compose.dev.yml
docker-compose.yml

- Add `make clean` to Makefile to clean out `node_modules` volume (and deletes the simpleimage container), this should be used whenever installing a new module to the project and the si container complains about dependency not found. Run `make build-dev` and `make clean` before running `make deploy-dev` in this case.
- Move Redis port settings to the dev config, as Redis should never be exposed to the outside world in production.

Update Docker config

---

lib/routes/route.js
lib/util.js
test/util_test.js
views/image-view.ejs
views/index.ejs
views/login-view.ejs
views/register-view.ejs
views/top-nav-view.ejs
views/user-menu-view.ejs
views/user-mobile-menu-view.ejs
views/user-view.ejs

https://owasp.org/www-community/attacks/Code_Injection
Code injections to vulnerable server routes are technically possible using query strings. I don't believe any of the routes within simpleimage can be exploited using this method. However, none of my redirect urls make use of query strings so they can be omitted.
Edit: Restrict redirect URLs further by only allowing redirects from a set list of redirects.

Add more restrictions to getRedirectPath

---

lib/routes/route.js
views/settings-view.ejs

`fromUrl` was removed in https://github.com/Coteh/simpleimage/commit/ac96c9fa00fd7daddf741570114f7d98e7f7354c but still existed in `settings` route. Removed it.
Fixes #135.

Remove fromUrl from settings-view endpoint

---

lib/routes/route.js

Addressing this issue:
> Cookie “connect.sid” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
Keeping in draft until I test it somehow locally. (perhaps by setting up local https server #182 or something else)

Add secure attribute to cookie

---

views/index.ejs

Updated Upload icon from "upload" icon in Collecticons library to "upload-2". IMO this alternative upload icon looks simpler and more sleek.
http://collecticons.io/

Change Upload icon

---

assets/css/style.css
lib/database-ops.js
package.json

Lock dropdown menu to right

---

assets/css/form-style.css
assets/js/main.js
lib/database-ops.js
lib/routes/route.js
lib/util/username.js
package-lock.json
package.json
test/integ/check_username_integ_test.js
test/util_test.js
views/register-view.ejs

Fixes #14.
When username is available, username field will be green.
When username is not available, username field will be red with error message below.
When long username is submitted, it will look like this. This is acceptable for now.
When other error occurs (e.g. rate limit error), there will be no highlight and no message. It would effectively look like the way it did before. I decided it would be better UX to not show an error in this case.

Add username check to signup form

---

lib/routes/route.js

Closes #70.
Seems like the only way to easily catch this error while server is running is by checking the string in error message. This is because the error is thrown by express-session during the route handling process, as seen [here](https://github.com/expressjs/session/blob/a8641429502fcc076c4b2dcbd6b2320891c1650c/index.js#L200). I prefer not to handle the error in this manner unless absolutely necessary, especially because the string can change any time in a future update of express-session.
Instead, I think it would actually make more sense if the server did not run at all if session secret were not provided. And in this PR, I have done just that. When app is set in production mode, it will throw an error and exit if secret is not provided. This avoids having to deal with the message …

Ensure a session secret is provided in production environment.

---

lib/util.js
package-lock.json
package.json
test/util_test.js

Closes #18 
- Also change apostrophe encode in tests since html-entities library uses `&apos;` instead of `&#39;`
- Also change undefined test case because html-entities returns empty string if undefined is passed in

Replace html encoding function with html-entities library

---

lib/routes/route.js

This would allow forked projects to run CI tests without requiring session secret. It seems like session secret can only be passed to forked projects in CircleCI if all secrets (env vars, etc.) are passed down, so this is a better alternative for now IMO.

Allow session secret to have a default value in dev and in test

---

README.md
assets/js/main.js
views/login-view.ejs
views/register-view.ejs

User name now auto-fills at register box if the user enters username in the username field of the login box and clicks the Register button.

Username auto fill fix

---

lib/comments.js
lib/database-ops.js
lib/routes/route.js
package-lock.json
package.json
test/comments_test.js
test/integ/change_password_integ_test.js
test/integ/check_user_login_integ_test.js
test/integ/integ_test_utils.js
test/integ/user_comments_integ_test.js
views/error.ejs
views/footer.ejs

Closes #13.
Other changes:
- Change all functions + url variable in database-ops to be const
- Extract performUserLogin from change password integ test so that it can be used in user comments integ test as well
- Alter both image and user comments HTML slightly so that properties are double quoted rather than single quoted
- Add Content-Type header to user comments response so that JSON user comments response has JSON Content-Type and thus can be parsed by superagent in integ test

Add image thumbnails to user comments section

---

.env.example
.gitpod.yml
README.md

Also contains an `.env.example` with some defaults for the docker-compose stack currently in the project.

Add Gitpod support

---

webpack.config.js

So that error does not appear when developing without a Sentry account.
Error looked something like this:
```
si-app         | ERROR in Sentry CLI Plugin: Command failed: /usr/src/simpleimage/node_modules/@sentry/cli/sentry-cli releases new simpleimage@1.3.1
si-app         | error: An organization slug is required (provide with --org)
si-app         |
si-app         | Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
si-app         | Please attach the full debug log to all bug reports.
```
Now it just emits information about the source map upload and current settings for Sentry plugin, but does not actually upload the source maps. (hence the dry run)
```
si-app         | [Sentry Webpack Plugin] Creating new release:
si-app         | …
```

Turn on dryRun mode for Sentry webpack plugin when in development mode.

---

alvarotorrestx.md
assets/css/form-style.css

- alvarotorrestx.md
- assets/css/form-style.css
I'm not 100% familiar yet with working with projects and databases, I updated the CSS that should resolve the styling fix and tested with Google Chrome DevTools, both with success and failure included.
Please update me if this was not resolved correctly and thank you for allowing me to contribute!

Fixes for Delete images prompt is not centered #278 

---

.circleci/config.yml
.circleci/images/primary/Dockerfile
.gitignore
README.md
docker-compose.test.yml
lib/database-ops.js
lib/route/upload/index.js
lib/server.js
package.json
test/integ/upload_integ_test.js
test/scripts/generate_large_image.sh

If omitted, the file size limit will default to 500 MB (which, up until now, was the hardcoded file limit)
Also remove comment reference to Heroku that I forgot to take out when migrating to Fly.io.
si-test-deps image was updated to include libvips, which is only used to create the large image for the large image test when running in CI.

Add the ability to set file size limit for images

---

assets/css/home-style.css
assets/css/style.css
assets/js/file-upload.js
cypress/e2e/1-homepage/home.cy.js
cypress/support/e2e.js
lib/consts.js
lib/route/index.js
lib/route/upload/index.js
lib/util.js
nodemon.json
package-lock.json
package.json
test/util_test.js
views/footer.ejs
views/image-view.ejs
views/index.ejs
views/login-view.ejs
views/register-view.ejs
views/settings-view.ejs
views/top-nav-view.ejs
views/user-view.ejs

Other Changes:
- Improve homepage layout, especially for mobile
- Move logo to middle of page in homepage, moves back up to the top left when image selected
- Change CSS selectors for some elements to use class selector instead of id selector
- Add cypress/ folder to nodemon.json so that server doesn't reload when cypress test file is updated
- Update copyright
- Add file size limit to image too large error message

Add info label to homepage detailing limits of image upload

---

cypress/e2e/6-settings/change-password.cy.js
cypress/support/commands.js
lib/route/register/index.js
lib/route/settings/index.js
test/integ/user_register_integ_test.js
views/settings-view.ejs

Other Changes:
- Password strength failure in change password will now report the newPasswordConfirm field in addition to the newPassword field in its response
- Notifications in change password page will now clear before a new notification is displayed
- Have password strength errors share the same error ID

Highlight error fields in change password form
